set(CLR_REPO_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR})
set(CLR_ENG_NATIVE_DIR ${CMAKE_CURRENT_LIST_DIR})
set(CLR_SRC_NATIVE_DIR ${CMAKE_CURRENT_LIST_DIR}/native)
set (CLR_ARTIFACTS_OBJ_DIR "${CMAKE_CURRENT_LIST_DIR}/build/artifacts")
